### ISSUE TITLE
Info command

### ISSUE THREAD

**Issue by Kemikals** [Cannot-Find-Symbol/learn-java-bot#11]
This command should allow any user to type !info topic and it display the message stored for that topic.

**Comment by Benlewis9000** [comment]
To add to this:
- Messages created & stored flexibly (Json? DB?) i.e. not hard coded
- Messages can be created via a command by select users e.g. `!info new <topic> <message>`
- `!info list` would display all available tags

**Comment by Kemikals** [comment]
Command is done, but enhancement is needed, will open on new issue
